.github/workflows/slack.yml

Updated repo name in slack workflow

---

action.yml
main.js
main.sh
meshery.sh
mesheryctl.sh

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
This PR fixes #4
* Currently creates a load test using the performance profile for a load test
* Doesn't take care of service meshes. (Need to identify where is https://github.com/service-mesh-performance/service-mesh-performance/blob/c35c9833ae994720bfd0fa9321406dbb9f2da2cb/protos/service_mesh.proto#L14 specified in a performance profile)
* Needs https://github.com/meshery/meshery/issues/3586

initial meshery-smp-action

---

action.yml
main.sh
meshery.sh
mesheryctl.sh

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
Supply a profile name, this action will deploy the service mesh specified in it and run the performance test. 

[Feature] run a performance test using profile name

---

main.sh

Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
Updated the logic for making the script executable. It is not a good approach to set the script executable like this `"$SCRIPT_DIR/meshery.sh" "${setupArgs[@]}"`

[CI] Updated the logic for making the script executable

---

.github/test-config.yaml
.github/workflows/scheduled-benchmarks.yml
.github/workflows/scripts/istio_deploy.sh
action.yml
main.sh
mesheryctl.sh

Updates the action to:
* support injecting dynamic endpoint urls (accompanying [PR in Meshery/mesheryctl](https://github.com/meshery/meshery/pull/4590))
* deploy adapters when running a test with a configuration file
Adds a new workflow that runs scheduled performance benchmarks that:
* Setups a Kubernetes cluster
* Deploys a service mesh and onboards an application (Currently only Istio. A build matrix or separate workflows can be made for benchmarking other service meshes as well)
* Deploys Meshery and Meshery Adapters
* Runs a performance test based on either the configuration file provided or a performance profile name
* The workflow can either be manually triggered or be scheduled to run at a fixed time (arbitrarily this is set to run every Thursday at 13:22)
* Both …

Scheduled workflow for running performance benchmarks

---

README.md

Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
This PR updates the README to mention the updated configuration options in the action.

Update examples in the README

---

.github/workflows/scripts/istio_deploy.sh

Signed-off-by: Xin Huang <xin1.huang@intel.com>
This PR fixes #27 
1. Replace `minikube tunnel` command with `minikube tunnel &> /dev/null &` to avoid the tunnel getting killed.
2. Change the default endpoint_url to make sure it's reachable from Meshery.

Ensure that Istio application endpoint is reachable from Meshery

---

.github/workflows/scheduled-benchmarks.yml
mesheryctl.sh

Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
Depends on https://github.com/meshery/meshery/pull/4710
Updates the performance profile names and the test names for easy access.
This needs to be tested after merging and making a new release with the PR linked above.
**Don't merge this PR.**

update performance profile name and test name in scheduled benchmarks

---

.github/workflows/configurable-benchmark-test.yaml

We are currently able to run Configurable-benchmark-test on Docker platform and bumps the setup minikube action version to 2.4.3.
Given that all the heavy lifting has been done with the instance and the OS permissions, the changes here are rather minor.
This new branch servers as a dev branch to while we figure out the self-hosted-runners piece.
Successful CI run :- https://github.com/hershd23/meshery-smp-action/runs/5173891017?check_suite_focus=true

Self hosted runner

---

.github/workflows/scripts/osm_deploy.sh

Was looking into this issue why builds been failing, find out that Open Service Mesh (OSM) CLI version was changed, also tried to simplify code to see what can I do to make it work.
Unsuccessful run on master here :- https://github.com/layer5io/meshery-smp-action/runs/5204098138?check_suite_focus=true
Successful run on your local fork :- https://github.com/AugustasV/meshery-smp-action/runs/5204058656?check_suite_focus=true

Fix scheduled builds

---

.github/workflows/configurable-benchmark-test-self-hosted.yaml
.github/workflows/configurable-benchmark-test.yaml
.github/workflows/scripts/self-hosted-credentails.sh
.github/workflows/scripts/start-cil-runner.sh
.github/workflows/scripts/stop-cil-runner.sh
meshery.sh

The commit automates below steps:
1. Create a CNCF CIL machine and register it as a self-hosted runner
2. Run SMP benchmarks on the self-hosted runner
3. Stop and remove the CNCF CIL machine and self-hosted runner
This PR fixes #38 

Automating initialization of on-demand self-hosted CNCF CIL runner

---

.github/workflows/configurable-benchmark-test-self-hosted.yaml
.github/workflows/scheduled-benchmarks-self-hosted.yaml
.github/workflows/scripts/start-cil-runner.sh
.github/workflows/scripts/stop-cil-runner.sh

**Description** 
This PR fixes https://github.com/layer5io/meshery-smp-action/issues/38, implements running scheduled benchmark test on self-hosted runner.
There are two method Scheduled benchmarking test can be triggered:
**Manual test**: we can trigger the test by giving specific test configurations (load-test, soak-test), then the matrix will be tested.
**Scheduled test**: the matrix test will run everyday.
There are three steps for scheduled benchmarking test like configurable benchmarking test: 
1. Create CNCF CIL machines and register them as github self-hosted runners
2. Install Kubernetes, Service mesh and meshery. Then run benchmarking tests.
3. Destroy machines and delete self-hosted runners. 
Workflows:
Github self-hosted runners:
CNCF CIL machines: …

Run scheduled benchmark test on self-hosted runner

---

.github/workflows/configurable-benchmark-test-self-hosted.yaml
.github/workflows/configurable-benchmark-test.yaml
.github/workflows/scheduled-benchmarks-self-hosted.yaml
.github/workflows/scripts/self-hosted-credentails.sh
.github/workflows/scripts/start-cil-runner.sh
.github/workflows/scripts/stop-cil-runner.sh
meshery.sh

Cherry-pick self hosted to master

---

.github/workflows/configurable-benchmark-test-self-hosted.yaml
.github/workflows/scheduled-benchmarks-self-hosted.yaml
.github/workflows/scripts/stop-cil-runner.sh

If it's a scheduled benchmark test, we retrives all devices to get
device id of each machine, which often cause failures due to its large
query. After this change, we use hostname to retrive device id of each
machine, it will fix above failures.
Signed-off-by: Huang Xin <xin1.huang@intel.com>

Fix stop runners failures

---

.github/workflows/configurable-benchmark-test-self-hosted.yaml
.github/workflows/scheduled-benchmarks-self-hosted.yaml

Signed-off-by: Huang Xin <xin1.huang@intel.com>
Add default timeouts for jobs to avoid workflow being always pending due to one failed job.

Add default timeouts for jobs

---

.github/workflows/scheduled-benchmarks-self-hosted.yaml
.github/workflows/scheduled-benchmarks.yml

Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>
This PR: 
1. Updates `install dependencies` step to create and give proper permission to `~/.kube` dir
2. Updates install minikube-setup action to the latest version.
Possibly aims to solve this problem:
https://github.com/layer5io/meshery-smp-action/runs/6424151872?check_suite_focus=true#step:7:1368

[Bug] Fix K8s config unavailable to Meshery server 

---

.github/workflows/scripts/istio_deploy.sh
.github/workflows/scripts/linkerd_deploy.sh
.github/workflows/scripts/osm_deploy.sh

Signed-off-by: Huang Xin <xin1.huang@intel.com>

Increase sleep time after mesh adapter deployment.

---

.github/workflows/scripts/istio_deploy.sh
.github/workflows/scripts/linkerd_deploy.sh
.github/workflows/scripts/osm_deploy.sh

Signed-off-by: Huang Xin <xin1.huang@intel.com>

Add more logs during the meshery installation.

---

.github/workflows/configurable-benchmark-test-self-hosted.yaml
.github/workflows/configurable-benchmark-test.yaml
.github/workflows/scheduled-benchmarks-self-hosted.yaml
.github/workflows/scheduled-benchmarks.yml
mesheryctl.sh

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
This PR fixes #68 
PR is WIP

Change k8s minikube action version and args 

---

.github/workflows/scripts/istio_deploy.sh
.github/workflows/scripts/linkerd_deploy.sh

Fixed pattern apply for istio and app onboard linkerd

---

.github/workflows/scripts/start-cil-runner.sh

Add termination time when creating servers.

---

.github/workflows/scripts/istio_deploy.sh
.github/workflows/scripts/linkerd_deploy.sh
.github/workflows/scripts/osm_deploy.sh

This PR fixes https://github.com/meshery/meshery/issues/10592
~DON'T MERGE UNLESS https://github.com/meshery/meshery/pull/11051 is merged!~
Update: PR is merged. Good to go

Rename pattern to design cmd in scripts
